### ISSUE TITLE
How to deploy and reload?

### ISSUE THREAD

**Issue by ddosoff** [igorcoding/tarantool-appstarter#1]
Hi, great work.

Could you describe a bit about deploying and hot app reload?

**Comment by igorcoding** [comment]
Hello, thank you for your question!

The main idea behind this appstarter is to provide you with a default approach of developing apps for Tarantool. 
To create a project starter you can run 
```
mkdir -p /path/to/app
tntstartapp /path/to/app
``` 

And you'll end up with a default structure of an app. There are some important parts in it:
1) `dep.py` and `meta.yaml`. Luarocks spec files does not support specifying dependencies on GH projects (via link to *.rockspec file), but the luarocks itself does. So, `meta.yaml` is a place where you drop your external dependencies (like a package.json for npm or requirements.txt for pip). You can specify either tarantool modules there (in the `tntdeps` section) by there names (like `queue` or `http`) or just bare links to *.rockspec files (in the `deps` section). Then a bundled `dep.py` script will use this `meta.yaml` file to install all the required dependencies to a specified location.
2) `Makefile`. There are 2 main commands there:
* `make dep` - This command installs all the dependencies from meta.yaml to a local folder `libs` inside your project (already in bundled .gitignore)
* `make run`. After a successful installation of dependencies you can run your application. Practically it just creates a temporary folder `tnt_{LISTEN_URI}`, `cd`'s inside and runs `tarantool init.lua`.
3) `init.lua` - An entry point to your entire application. Specifically, it does this:
* patches package.path and package.cpath to import packages from ./libs and ./app folders directly.
* `require`'s [package.reload module](https://github.com/Mons/tnt-package-reload)
* `require`'s config module (please refer to @mons's [tnt-config module](https://github.com/Mons/tnt-config) for more details). By default (if not specified in ENV variable CONF) it uses config file from /etc/{your_app_name}/conf.lua
* Runs `require('app')`. Which is essentially is run of your application.
* Also it starts the interactive console immediately (so you don't need to explicitly connect to your Tarantool instance)
4) `app`. This is a directory that contains all of your application code. It is absolutely up to you how you organize your code in this folder. By default `app/init.lua` `require`'s your inner application module and registers in the package-reload module. So when code reload happens, the `destroy` function of your module is called (to cleanup resources, stop fibers or whatever you want).

So, back to your question.
There is a bundled rpm spec for this project template (I'm not sure it is super-classy, but still gives some intuition on how to deploy this kind of apps). As described in readme the project deploys to the following structure:
```
/
├── etc
│   └── {{__appname__}}
│       └── conf.lua
└── usr
    └── share
        └── {{__appname__}}
            ├── init.lua
            ├── app/
            └── libs/
```

As you can see, `init.lua`, `app folder` and `libs folder` (so you, obviously, need to bundle your dep or rpm package with your dependencies) deploy to `/usr/share/{appname}/`, and `conf.lua` deploys to `/etc/{appname}/conf.lua`. So in order to run your applcation by either `tarantoolctl` or `systemd` you just put a symlink `/etc/tarantool/instances.enabled/{appname}.lua -> /usr/share/{appname}/init.lua` and you are ready to execute either `tarantoolctl start {appname}` or `systemctl start tarantool@appname`.

After all of that, if you want to hot-reload your application you just deploy your new code, connect to your running instance by any preferred method (for example, by executing `tarantoolctl enter {appname}`) and just run `package.reload()`. That should be it.

If you still have any questions - feel free to ask.

**Comment by ddosoff** [comment]
Thanks. It's clear to me how deploy works app with rpm. This text should be in README.md for sure.

Did you try it on Debian based distros?

**Comment by igorcoding** [comment]
Yeah, I'll put this into README of course.
Well, essentially everything is the same for the Debian distros:
* you put your `init.lua`, `app` and `libs` folder to `/usr/share/{appname}/`, 
* put `conf.lua` to `/etc/{appname}/`
* make a symlink `/etc/tarantool/instances.enabled/{appname}.lua -> /usr/share/{appname}/init.lua`

I can try to make an example of deb specs, if you want.

**Comment by ddosoff** [comment]
Why not use default tarantool directories to put app:

/usr/share/tarantool/{appname}/
/etc/tarantool/{appname}/conf.lua

?

**Comment by igorcoding** [comment]
You can, there was no specific reason to use other locations than tarantool defaults, it just seems natural, with minimum dependency on tarantool itself. I considered /usr/share/tarantool more as a location to install external modules, rather than applications directory, but maybe there is something in it, I'll think about it.

**Comment by ddosoff** [comment]
Could you give a small example of real config?

According to https://github.com/Mons/tnt-config/blob/master/config.lua we have two types of node parameters - **dynamic** and **static**. How to use them?

**Comment by igorcoding** [comment]
example of config is already in template - conf.lua

You actually shouldn't bother about dynamic or static settings - they are all the same parameters as in `box.cfg{}`. So you put to box = { } table in conf.lua everything you would originally put inside box.cfg{}.

This separation (to dynamic and static params) is due to package.reload(), because only dynamic parameters (such as listen or wal_mode) can be redefined on reload, but static parameters can only be defined on the server startup (such as work_dir, for example), so this sepration only needed internally to throw an error if you changed some of static params and trying to package.reload().

**Comment by ddosoff** [comment]
Thank you very match. I started my app using appstarter. Very comfortably.
